language: c
compiler:
  - gcc
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pkg-config gnome-doc-utils libglib2.0-dev libgpgme11-dev
script:
  - ./autogen.sh
  - ./configure --disable-mono && make && make check
